name: lepfe
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  page_transition: ^2.1.0
  animated_bottom_navigation_bar: ^1.3.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  get: ^4.6.1
  # DateTime
  jiffy: ^6.2.1
  intl: ^0.18.1
  http: ^1.2.1
  # Images
  cached_network_image: ^3.2.0
  image_picker: ^1.0.7
  # Animate
  show_up_animation: ^2.0.0
  auto_animated: ^3.0.1
  # Google Map
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.1.5
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  # Firebase And Notification
  firebase_messaging: ^14.8.0
  firebase_core: ^2.28.0
  flutter_local_notifications: ^17.0.0
  cloud_firestore: ^4.16.0
  # Local Data Cache
  sqflite: ^2.0.2
  shared_preferences: ^2.0.15
  path: ^1.8.0
  # Qrcode
  qr_flutter: ^4.0.0
  scan: ^1.6.0
  grouped_list: ^5.1.2
  url_launcher: ^6.1.2
  dropdown_search: ^5.0.6
  badges: ^3.1.2
  # Icon
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.1.0
  fluttericon: ^2.0.0
  dartz: ^0.10.1
  # Google Auth
  google_sign_in: ^6.2.1
  device_preview: ^1.1.0
  responsive_builder: ^0.7.0
  image_pickers: ^2.0.0+2
  flutter_otp_text_field: ^1.1.3+2
  google_generative_ai: ^0.3.2
intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^3.0.0  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700