name: lepfe
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.2.1
  fl_chart: ^0.68.0
  simple_animation_progress_bar: ^1.6.0
  dotted_dashed_line: ^0.0.3
  simple_circular_progress_bar: ^1.0.2
  animated_toggle_switch: ^0.6.2
  readmore: ^2.1.0
  calendar_agenda:
    path: dev_lib/calendar_agenda/
  intl: ^0.18.1
dependency_overrides:
  intl: ^0.18.1
  page_transition: ^2.1.0
  animated_bottom_navigation_bar: ^1.3.3
  get: ^4.6.1
  jiffy: ^6.2.1

  http: ^1.2.1
  cached_network_image: ^3.2.0
  image_picker: ^0.8.9
  show_up_animation: ^2.0.0
  auto_animated: ^3.0.1
  animated_theme_switcher: ^2.0.1-nullsafety.0
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.1.5
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  firebase_messaging: ^14.8.0
  firebase_core: ^2.28.0
  flutter_local_notifications: ^17.0.0
  cloud_firestore: ^4.16.0
  sqflite: ^2.0.2
  shared_preferences: ^2.0.15
  flutter_iconly: 1.0.2
  path: ^1.8.0
  qr_flutter: ^4.0.0
  scan: ^1.6.0
  grouped_list: ^5.1.2
  url_launcher: ^6.1.2
  dropdown_search: ^5.0.6
  badges: ^3.1.2
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.1.0
  fluttericon: ^2.0.0
  dartz: ^0.10.1
  google_sign_in: ^6.2.1
  device_preview: ^1.1.0
  responsive_builder: ^0.7.0
  image_pickers: ^2.0.0+2
  pin_code_fields: ^8.0.1
  flutter_otp_text_field: ^1.1.3+2
  google_generative_ai: ^0.3.2
  visibility_detector: ^0.4.0+2
  dotted_border:
    #le Scan
  flutter_tflite: ^1.0.1
  permission_handler: ^11.3.1
  camera: ^0.10.6
  image: ^3.3.0
  lottie: ^2.7.0
  flutter_markdown: ^0.6.18+2
  flutter_gemini: ^2.0.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/
    - assets/
    - assets/img/
    - assets/xx.png
    - assets/mechil.jpg
    - assets/wlyam.jpg
    - assets/mic.png
  fonts:

    - family: Poppins
    - family: Cairo
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
